# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treemenus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='root_item',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_root_item_of', to='treemenus.MenuItem', verbose_name='root item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treemenus.MenuItem', verbose_name='parent'),
        ),
    ]
